"""
Signal domain model.

Represents a trading signal generated by a strategy.
Includes direction, confidence, suggested sizing, and reasoning.
"""

from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import Any
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class SignalDirection(str, Enum):
    """Signal direction."""

    LONG = "LONG"  # Buy signal
    SHORT = "SHORT"  # Sell signal
    FLAT = "FLAT"  # Exit/no position signal


class Signal(BaseModel):
    """
    A trading signal from a strategy.

    Contains all information needed to make a trading decision,
    including the reasoning for audit purposes.
    """

    # Identification
    id: UUID = Field(
        default_factory=uuid4,
        description="Unique signal identifier",
    )
    strategy_id: str = Field(
        ...,
        description="Identifier of the strategy that generated this signal",
    )
    symbol: str = Field(
        ...,
        description="Instrument symbol",
    )
    timestamp: datetime = Field(
        ...,
        description="Signal generation timestamp (UTC)",
    )

    # Signal details
    direction: SignalDirection = Field(
        ...,
        description="Signal direction (LONG/SHORT/FLAT)",
    )
    confidence: Decimal = Field(
        default=Decimal("1.0"),
        description="Signal confidence (0.0 to 1.0)",
        ge=0,
        le=1,
    )

    # Suggested parameters
    entry_price: Decimal | None = Field(
        default=None,
        description="Suggested entry price (if limit order)",
        gt=0,
    )
    stop_loss: Decimal | None = Field(
        default=None,
        description="Suggested stop loss price",
        gt=0,
    )
    take_profit: Decimal | None = Field(
        default=None,
        description="Suggested take profit price",
        gt=0,
    )
    size_hint: Decimal | None = Field(
        default=None,
        description="Suggested position size",
        gt=0,
    )

    # Context and reasoning
    bar_timestamp: datetime | None = Field(
        default=None,
        description="Timestamp of the bar that triggered this signal",
    )
    reason_codes: list[str] = Field(
        default_factory=list,
        description="Reason codes explaining why signal was generated",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional strategy-specific metadata",
    )

    class Config:
        frozen = True  # Immutable once created

    @property
    def is_entry(self) -> bool:
        """Check if this is an entry signal."""
        return self.direction in (SignalDirection.LONG, SignalDirection.SHORT)

    @property
    def is_exit(self) -> bool:
        """Check if this is an exit signal."""
        return self.direction == SignalDirection.FLAT

    @property
    def is_long(self) -> bool:
        """Check if this is a long signal."""
        return self.direction == SignalDirection.LONG

    @property
    def is_short(self) -> bool:
        """Check if this is a short signal."""
        return self.direction == SignalDirection.SHORT

    def __hash__(self) -> int:
        return hash(self.id)
